name: Deploy PsicoCare

on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run tests
        run: ./gradlew test
      - name: Build project
        run: ./gradlew clean assemble
      - name: Login Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t dracarys22/deploy_psicocare .
      - name: Push image docker
        run: docker push dracarys22/deploy_psicocare
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull ima from docker hub
        run: docker pull dracarys22/deploy_psicocare:latest
      - name: Run docker container
        run: |
          docker run -d -p 8080:8080 \
          -e DB_USERNAME=${{secrets.DB_USERNAME}} \
          -e DB_PASSWORD=${{secrets.DB_PASSWORD}} \
          -e POSTGRES_URL=${{secrets.POSTGRES_URL}} \
          -e MAIL_USERNAME=${{secrets.MAIL_USERNAME}} \
          -e MAIL_PASSWORD=${{secrets.MAIL_PASSWORD}} \
          --name deploy_psicocare \
          dracarys22/deploy_psicocare:latest
